{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "formae.fullname" . }}-postgresql
  labels:
    {{- include "formae.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
