{{- if and (eq .Values.formae.datastore.type "postgres") (not .Values.postgresql.enabled) (not .Values.formae.datastore.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "formae.fullname" . }}-db
  labels:
    {{- include "formae.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.formae.datastore.postgres.password | b64enc | quote }}
{{- end }}
